# Exception handling

To anticipate exceptions,
we use try/except blocks.

## Method 1

```python
lst = [1, 2, 3]
index = int(input("Enter an index: "))
if 0 <= index < len(lst):
    value = lst[index]
else:
    print("Value is out of range, doofus!")
```

## Method 2

```python
lst = [1, 2, 3]
index = int(input("Enter an index: "))
try:
    value = lst[index]
except IndexError:
    print("Value is out of range, doofus!")
except LookupError:
    print("I failed to look something up!")
except:
    print("Something else went wrong!")
else:
    print("Nothing went wrong.")
```

## The anatomy of a try/except

There must be:
* at most one `try` branch/block
* at least one `except` branch/block
    - A 'catch-all' `except` branch must be at the end
      of all other branches.
* at most one `else` branch
    - This gets executed if no exceptions were raised
      while we were executing the `try` block.

An except branch names a specific error.
There may be a default branch which catches all errors.

## Terminology

* Exceptions
    - Errors in our program we can catch
      in a `try/except` block
* Raise
    - The 'happening' of an error.


## Except-as

If we want to inspect an error,
and see what *exactly* happened,
we can write `except Exception as varname`


